version: '3.8'

services:
  db:
    image: 'postgres:14'
    ports:
      - '8433:5432'
    environment:
      PGPASSWORD: 'password'
      POSTGRES_DB: 'immersion-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - 'immersion-go-pgsql:/var/lib/postgresql/data'
#      - './docker/db_preload.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - immersion-go-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "immersion-db", "-U", "postgres" ]
      retries: 3
      timeout: 5s

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_ERLANG_COOKIE: "aVerySecureCookieString123!"
      RABBITMQ_DEFAULT_USER: "rabbitmq_user"
      RABBITMQ_DEFAULT_PASS: "rabbitmq_password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - 'immersion-go-rabbitmq-data:/var/lib/rabbitmq/mnesia'
      - 'immersion-go-rabbitmq-logs:/var/log/rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - immersion-go-net

networks:
  immersion-go-net:
    driver: bridge
volumes:
  immersion-go-pgsql:
    driver: local
  immersion-go-rabbitmq-data:
    driver: local
  immersion-go-rabbitmq-logs:
    driver: local
